### ISSUE TITLE
Mutable default in dataclass

### ISSUE THREAD

**Issue by wazizian** [inria-thoth/mlxp#4]
Hi,
I was trying out this package (which looks great!) nut I run into an issue.
On Python 3.11.4, with both the stable release of `mlxp` and the GitHub version, I obtain the following error when trying to import the package.
```python
Python 3.11.4 (main, Jul  5 2023, 14:15:25) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mlxp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wazizian/miniconda3/lib/python3.11/site-packages/mlxp/__init__.py", line 3, in <module>
    from mlxp.launcher import Context, launch
  File "/home/wazizian/miniconda3/lib/python3.11/site-packages/mlxp/launcher.py", line 22, in <module>
    from mlxp._internal.configure import _build_config, _process_config_path
  File "/home/wazizian/miniconda3/lib/python3.11/site-packages/mlxp/_internal/configure.py", line 9, in <module>
    from mlxp.data_structures.schemas import Metadata
  File "/home/wazizian/miniconda3/lib/python3.11/site-packages/mlxp/data_structures/schemas.py", line 228, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/wazizian/miniconda3/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/wazizian/miniconda3/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wazizian/miniconda3/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wazizian/miniconda3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'mlxp.data_structures.schemas.ConfigLogger'> for field logger is not allowed: use default_factory
```
Have you got this issue as well? On which version of Python do you usually run this package?

**Comment by MichaelArbel** [comment]
Hi, thanks for reporting this bug! 


It looks like the behavior of dataclasses changed on python 3.11, which causes this error. 
I'll look into this it soon. 

Meanwhile, the package should work on earlier versions of python (3.10, 3.9, 3.8)

**Comment by wazizian** [comment]
Thank you!
But don't worry of you don't have time, I see now, I can try to submit a PR when I come back to this :-)

**Comment by MichaelArbel** [comment]
Hello, 

The new release 0.1.2 should solve this issue. 
Please let me know if you encounter other issues with this version. 

Cheers,

**Comment by wazizian** [comment]
Indeed, thank you !
